import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { calculateQuizCount, runStudy, verifyEvidenceIndexReport, verifyHtmlExportManifest, verifyStudySessionArtifacts, writeHtmlZipBundle } from "./index.js";

const fixtureRoot = path.resolve("packages/core/tests/fixtures/simple-ts-app");

describe("RepoTutor core pipeline", () => {
  it("generates a complete study session for a TypeScript fixture", async () => {
    const studiesRoot = await fs.mkdtemp(path.join(os.tmpdir(), "repotutor-study-"));
    const result = await runStudy({ source: fixtureRoot, mode: "quick", level: "beginner", studiesRoot });
    expect(result.session.status).toBe("complete");
    expect(result.session.quizSummary.totalQuestions).toBeGreaterThanOrEqual(5);
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "repo-map.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "evidence-index-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "suggested-reads-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "runtime-environment-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "interface-map-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "symbol-map-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "api-reference-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "search-index-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "learning-journal-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "project-activity-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "license-rights-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "sbom-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "security-readiness-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "context-pack-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "mcp-handoff-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "agent-memory-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "graph-query-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "tutorial-abstraction-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "decision-record-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "dependency-health-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.analysis, "session-verification-report.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "overview.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "component-graph.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "incremental.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "evidence.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "suggested-reads.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "runtime-environment.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "interface-map.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "symbol-map.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "api-reference.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "search-index.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "learning-journal.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "project-activity.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "license-rights.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "sbom.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "security-readiness.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "context-pack.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "mcp-handoff.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "agent-memory.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "graph-query.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "tutorial-abstractions.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "decision-records.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "dependency-health.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.markdown, "session-verification.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "index.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "learning-path.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "manifest.json"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "EXPORT-README.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "component-graph.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "incremental.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "evidence.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "suggested-reads.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "runtime-environment.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "interface-map.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "symbol-map.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "api-reference.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "search-index.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "learning-journal.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "project-activity.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "license-rights.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "sbom.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "security-readiness.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "context-pack.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "mcp-handoff.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "agent-memory.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "graph-query.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "tutorial-abstractions.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "decision-records.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "dependency-health.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "session-verification.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "quiz-print.html"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.html, "assets", "learning-journal-template.md"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.codex, "events.jsonl"))).resolves.toBeUndefined();
    await expect(fs.access(path.join(result.session.outputPaths.source, ".env"))).rejects.toThrow();
    const snapshotText = await fs.readFile(path.join(result.session.outputPaths.analysis, "source-snapshot-report.json"), "utf8");
    expect(snapshotText).toContain("\"sha256\"");
    const coverageText = await fs.readFile(path.join(result.session.outputPaths.analysis, "coverage-report.json"), "utf8");
    expect(coverageText).toContain("\"evidenceBackedFiles\"");
    expect(coverageText).toContain("\"evidenceCoverageRatio\"");
    expect(coverageText).toContain("\"evidenceKindCounts\"");
    const incrementalText = await fs.readFile(path.join(result.session.outputPaths.analysis, "incremental-report.json"), "utf8");
    expect(incrementalText).toContain("\"baselineSessionId\"");
    expect(incrementalText).toContain("\"coverageDelta\"");
    const graphText = await fs.readFile(path.join(result.session.outputPaths.analysis, "component-graph-report.json"), "utf8");
    expect(graphText).toContain("\"nodes\"");
    expect(graphText).toContain("\"edges\"");
    expect(graphText).toContain("\"nodeTypeCounts\"");
    expect(graphText).toContain("\"topConnectedNodes\"");
    const componentGraphMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "component-graph.md"), "utf8");
    expect(componentGraphMarkdown).toContain("## 큰 그래프 요약");
    const componentGraphHtml = await fs.readFile(path.join(result.session.outputPaths.html, "component-graph.html"), "utf8");
    expect(componentGraphHtml).toContain("큰 그래프 요약");
    expect(componentGraphHtml).toContain("data-graph-filter");
    expect(componentGraphHtml).toContain("data-node-type");
    expect(componentGraphHtml).toContain("component-graph-download-toolbar");
    expect(componentGraphHtml).toContain("data-download-mermaid");
    expect(componentGraphHtml).toContain("component-graph-mermaid");
    expect(componentGraphHtml).toContain("component-node-relations");
    expect(componentGraphHtml).toContain("data-node-relation");
    expect(componentGraphHtml).toContain("연결 관계");
    expect(componentGraphHtml).toContain("component-node-anchor");
    expect(componentGraphHtml).toContain("data-node-id");
    expect(componentGraphHtml).toContain("data-node-link");
    expect(componentGraphHtml).toContain("href=\"#component-node-");
    const componentGraphMermaid = await fs.readFile(path.join(result.session.outputPaths.html, "assets", "component-graph.mmd"), "utf8");
    expect(componentGraphMermaid).toContain("flowchart");
    const learningPathTourText = await fs.readFile(path.join(result.session.outputPaths.html, "assets", "learning-path.tour.json"), "utf8");
    expect(learningPathTourText).toContain("RepoTutor Learning Path");
    expect(learningPathTourText).toContain("\"isPrimary\": true");
    expect(learningPathTourText).toContain("\"file\": \"html/component-graph.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/dependency-health.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/api-reference.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/search-index.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/learning-journal.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/project-activity.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/license-rights.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/sbom.html\"");
    expect(learningPathTourText).toContain("\"file\": \"html/security-readiness.html\"");
    const coverageHtml = await fs.readFile(path.join(result.session.outputPaths.html, "coverage.html"), "utf8");
    expect(coverageHtml).toContain("소스 근거 파일");
    expect(coverageHtml).toContain("근거 비율");
    expect(coverageHtml).toContain("소스 근거 종류");
    expect(coverageHtml).toContain("entry:");
    expect(coverageHtml).toContain("소스 근거 부족");
    const coverageMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "coverage.md"), "utf8");
    expect(coverageMarkdown).toContain("## 소스 근거 종류");
    expect(coverageMarkdown).toContain("- entry:");
    const suggestedReadsText = await fs.readFile(path.join(result.session.outputPaths.analysis, "suggested-reads-report.json"), "utf8");
    expect(suggestedReadsText).toContain("Repo Baby suggested_reads");
    expect(suggestedReadsText).toContain("\"items\"");
    const suggestedReadsHtml = await fs.readFile(path.join(result.session.outputPaths.html, "suggested-reads.html"), "utf8");
    expect(suggestedReadsHtml).toContain("추천 읽기");
    expect(suggestedReadsHtml).toContain("suggested-read-card");
    expect(suggestedReadsHtml).toContain("data-source-pattern=\"Repo Baby\"");
    const suggestedReadsMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "suggested-reads.md"), "utf8");
    expect(suggestedReadsMarkdown).toContain("# 추천 읽기");
    expect(suggestedReadsMarkdown).toContain("Source pattern: Repo Baby");
    const runtimeEnvironmentText = await fs.readFile(path.join(result.session.outputPaths.analysis, "runtime-environment-report.json"), "utf8");
    expect(runtimeEnvironmentText).toContain("docSmith Dockerfile and Docker Compose generation prompts");
    expect(runtimeEnvironmentText).toContain("\"setupSignals\"");
    const runtimeEnvironmentHtml = await fs.readFile(path.join(result.session.outputPaths.html, "runtime-environment.html"), "utf8");
    expect(runtimeEnvironmentHtml).toContain("실행 환경");
    expect(runtimeEnvironmentHtml).toContain("runtime-env-card");
    expect(runtimeEnvironmentHtml).toContain("data-source-pattern=\"docSmith\"");
    const runtimeEnvironmentMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "runtime-environment.md"), "utf8");
    expect(runtimeEnvironmentMarkdown).toContain("# 실행 환경");
    expect(runtimeEnvironmentMarkdown).toContain("Source pattern: docSmith");
    const interfaceMapText = await fs.readFile(path.join(result.session.outputPaths.analysis, "interface-map-report.json"), "utf8");
    expect(interfaceMapText).toContain("repomap page routes GraphQL REST data flow analysis");
    expect(interfaceMapText).toContain("\"routeSignals\"");
    const interfaceMapHtml = await fs.readFile(path.join(result.session.outputPaths.html, "interface-map.html"), "utf8");
    expect(interfaceMapHtml).toContain("인터페이스 맵");
    expect(interfaceMapHtml).toContain("interface-map-card");
    expect(interfaceMapHtml).toContain("data-source-pattern=\"repomap\"");
    const interfaceMapMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "interface-map.md"), "utf8");
    expect(interfaceMapMarkdown).toContain("# 인터페이스 맵");
    expect(interfaceMapMarkdown).toContain("Source pattern: repomap");
    const symbolMapText = await fs.readFile(path.join(result.session.outputPaths.analysis, "symbol-map-report.json"), "utf8");
    expect(symbolMapText).toContain("codebase-map AST-based functions classes constants index");
    expect(symbolMapText).toContain("\"symbolsByKind\"");
    const symbolMapHtml = await fs.readFile(path.join(result.session.outputPaths.html, "symbol-map.html"), "utf8");
    expect(symbolMapHtml).toContain("심볼 맵");
    expect(symbolMapHtml).toContain("symbol-map-card");
    expect(symbolMapHtml).toContain("symbol-source-link");
    expect(symbolMapHtml).toContain("data-source-pattern=\"codebase-map\"");
    const symbolMapMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "symbol-map.md"), "utf8");
    expect(symbolMapMarkdown).toContain("# 심볼 맵");
    expect(symbolMapMarkdown).toContain("Source pattern: codebase-map");
    const apiReferenceText = await fs.readFile(path.join(result.session.outputPaths.analysis, "api-reference-report.json"), "utf8");
    expect(apiReferenceText).toContain("TypeDoc entry points reflections ReflectionKind public API documentation export validation");
    expect(apiReferenceText).toContain("\"entryPoints\"");
    expect(apiReferenceText).toContain("\"publicSymbols\"");
    expect(apiReferenceText).toContain("\"exportWarnings\"");
    const apiReferenceHtml = await fs.readFile(path.join(result.session.outputPaths.html, "api-reference.html"), "utf8");
    expect(apiReferenceHtml).toContain("API Reference");
    expect(apiReferenceHtml).toContain("api-reference-card");
    expect(apiReferenceHtml).toContain("data-source-pattern=\"TypeDoc\"");
    expect(apiReferenceHtml).toContain("ReflectionKind");
    const apiReferenceMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "api-reference.md"), "utf8");
    expect(apiReferenceMarkdown).toContain("# API Reference");
    expect(apiReferenceMarkdown).toContain("Source pattern: TypeDoc");
    expect(apiReferenceMarkdown).toContain("## Public Symbols");
    const searchIndexText = await fs.readFile(path.join(result.session.outputPaths.analysis, "search-index-report.json"), "utf8");
    expect(searchIndexText).toContain("Pagefind PageFragmentData MetaIndex filters meta_fields static low-bandwidth search index");
    expect(searchIndexText).toContain("\"documents\"");
    expect(searchIndexText).toContain("\"termIndex\"");
    expect(searchIndexText).toContain("\"filterIndex\"");
    expect(searchIndexText).toContain("\"metadataFields\"");
    const searchIndexHtml = await fs.readFile(path.join(result.session.outputPaths.html, "search-index.html"), "utf8");
    expect(searchIndexHtml).toContain("Search Index");
    expect(searchIndexHtml).toContain("search-index-card");
    expect(searchIndexHtml).toContain("data-source-pattern=\"Pagefind\"");
    expect(searchIndexHtml).toContain("PageFragmentData");
    expect(searchIndexHtml).toContain("MetaIndex");
    const searchIndexMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "search-index.md"), "utf8");
    expect(searchIndexMarkdown).toContain("# Search Index");
    expect(searchIndexMarkdown).toContain("Source pattern: Pagefind");
    expect(searchIndexMarkdown).toContain("## Filter Index");
    const searchIndexAsset = await fs.readFile(path.join(result.session.outputPaths.html, "assets", "search-index.json"), "utf8");
    expect(searchIndexAsset).toContain("\"documents\"");
    expect(searchIndexAsset).toContain("\"termIndex\"");
    const learningJournalText = await fs.readFile(path.join(result.session.outputPaths.analysis, "learning-journal-report.json"), "utf8");
    expect(learningJournalText).toContain("learn-codebase Socratic tutor active recall prediction before revelation persistent learning journal");
    expect(learningJournalText).toContain("\"focusGoals\"");
    expect(learningJournalText).toContain("\"masteryLevels\"");
    expect(learningJournalText).toContain("\"openQuestions\"");
    expect(learningJournalText).toContain("\"spacedReviewQueue\"");
    expect(learningJournalText).toContain("\"socraticPrompts\"");
    expect(learningJournalText).toContain("\"journalTemplateMarkdown\"");
    const learningJournalHtml = await fs.readFile(path.join(result.session.outputPaths.html, "learning-journal.html"), "utf8");
    expect(learningJournalHtml).toContain("Learning Journal");
    expect(learningJournalHtml).toContain("learning-journal-card");
    expect(learningJournalHtml).toContain("data-source-pattern=\"learn-codebase\"");
    expect(learningJournalHtml).toContain("Active Recall Journal");
    expect(learningJournalHtml).toContain("Spaced Review Queue");
    const learningJournalMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "learning-journal.md"), "utf8");
    expect(learningJournalMarkdown).toContain("# Learning Journal");
    expect(learningJournalMarkdown).toContain("Source pattern: learn-codebase");
    expect(learningJournalMarkdown).toContain("## Open Questions");
    expect(learningJournalMarkdown).toContain("## Spaced Review Queue");
    const learningJournalTemplateAsset = await fs.readFile(path.join(result.session.outputPaths.html, "assets", "learning-journal-template.md"), "utf8");
    expect(learningJournalTemplateAsset).toContain("# Codebase Learning Journal");
    expect(learningJournalTemplateAsset).toContain("## Concept Mastery Map");
    const projectActivityText = await fs.readFile(path.join(result.session.outputPaths.analysis, "project-activity-report.json"), "utf8");
    expect(projectActivityText).toContain("Repowise git analytics code health hotspots ownership co-change dead code architectural decisions MCP risk");
    expect(projectActivityText).toContain("\"historyAvailability\"");
    expect(projectActivityText).toContain("\"activitySignals\"");
    expect(projectActivityText).toContain("\"hotspotCandidates\"");
    expect(projectActivityText).toContain("\"deadCodeCandidates\"");
    expect(projectActivityText).toContain("\"reviewQueues\"");
    expect(projectActivityText).toContain("\"architectureDecisionPrompts\"");
    const projectActivityHtml = await fs.readFile(path.join(result.session.outputPaths.html, "project-activity.html"), "utf8");
    expect(projectActivityHtml).toContain("Project Activity");
    expect(projectActivityHtml).toContain("project-activity-card");
    expect(projectActivityHtml).toContain("data-source-pattern=\"Repowise\"");
    expect(projectActivityHtml).toContain("Project Activity Snapshot");
    expect(projectActivityHtml).toContain("history mode");
    const projectActivityMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "project-activity.md"), "utf8");
    expect(projectActivityMarkdown).toContain("# Project Activity");
    expect(projectActivityMarkdown).toContain("Source pattern: Repowise");
    expect(projectActivityMarkdown).toContain("## History Availability");
    expect(projectActivityMarkdown).toContain("## Review Queues");
    const licenseRightsText = await fs.readFile(path.join(result.session.outputPaths.analysis, "license-rights-report.json"), "utf8");
    expect(licenseRightsText).toContain("Licensee license file detection filename score SPDX confidence matched_files package metadata README references human compliance review");
    expect(licenseRightsText).toContain("\"detectedProjectLicense\"");
    expect(licenseRightsText).toContain("\"licenseFiles\"");
    expect(licenseRightsText).toContain("\"packageLicenseSignals\"");
    expect(licenseRightsText).toContain("\"readmeLicenseReferences\"");
    expect(licenseRightsText).toContain("\"reviewWarnings\"");
    expect(licenseRightsText).toContain("\"rightsChecklist\"");
    expect(licenseRightsText).toContain("No project license could be detected");
    const licenseRightsHtml = await fs.readFile(path.join(result.session.outputPaths.html, "license-rights.html"), "utf8");
    expect(licenseRightsHtml).toContain("License Rights");
    expect(licenseRightsHtml).toContain("license-rights-card");
    expect(licenseRightsHtml).toContain("data-source-pattern=\"Licensee\"");
    expect(licenseRightsHtml).toContain("License Rights Snapshot");
    const licenseRightsMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "license-rights.md"), "utf8");
    expect(licenseRightsMarkdown).toContain("# License Rights");
    expect(licenseRightsMarkdown).toContain("Source pattern: Licensee");
    expect(licenseRightsMarkdown).toContain("## Rights Checklist");
    expect(licenseRightsMarkdown).toContain("## Review Warnings");
    const sbomText = await fs.readFile(path.join(result.session.outputPaths.analysis, "sbom-report.json"), "utf8");
    expect(sbomText).toContain("Syft SBOM source descriptor artifacts packages file metadata relationships CycloneDX SPDX output formats");
    expect(sbomText).toContain("\"sourceDescriptor\"");
    expect(sbomText).toContain("\"packageManifests\"");
    expect(sbomText).toContain("\"packageArtifacts\"");
    expect(sbomText).toContain("\"fileArtifacts\"");
    expect(sbomText).toContain("\"relationships\"");
    expect(sbomText).toContain("\"outputFormats\"");
    expect(sbomText).toContain("\"purl\"");
    expect(sbomText).toContain("zod");
    const sbomHtml = await fs.readFile(path.join(result.session.outputPaths.html, "sbom.html"), "utf8");
    expect(sbomHtml).toContain("SBOM");
    expect(sbomHtml).toContain("sbom-card");
    expect(sbomHtml).toContain("data-source-pattern=\"Syft\"");
    expect(sbomHtml).toContain("SBOM Snapshot");
    const sbomMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "sbom.md"), "utf8");
    expect(sbomMarkdown).toContain("# SBOM");
    expect(sbomMarkdown).toContain("Source pattern: Syft");
    expect(sbomMarkdown).toContain("## Package Artifacts");
    expect(sbomMarkdown).toContain("## Output Formats");
    const securityReadinessText = await fs.readFile(path.join(result.session.outputPaths.analysis, "security-readiness-report.json"), "utf8");
    expect(securityReadinessText).toContain("Trivy targets scanners vulnerability secret misconfiguration license SBOM severity security readiness");
    expect(securityReadinessText).toContain("\"scannerTargets\"");
    expect(securityReadinessText).toContain("\"scannerCoverage\"");
    expect(securityReadinessText).toContain("\"securitySignals\"");
    expect(securityReadinessText).toContain("\"actionQueue\"");
    expect(securityReadinessText).toContain("\"recommendedCommands\"");
    expect(securityReadinessText).toContain("trivy fs --scanners vuln,secret,misconfig,license");
    const securityReadinessHtml = await fs.readFile(path.join(result.session.outputPaths.html, "security-readiness.html"), "utf8");
    expect(securityReadinessHtml).toContain("Security Readiness");
    expect(securityReadinessHtml).toContain("security-readiness-card");
    expect(securityReadinessHtml).toContain("data-source-pattern=\"Trivy\"");
    expect(securityReadinessHtml).toContain("Security Readiness Snapshot");
    const securityReadinessMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "security-readiness.md"), "utf8");
    expect(securityReadinessMarkdown).toContain("# Security Readiness");
    expect(securityReadinessMarkdown).toContain("Source pattern: Trivy");
    expect(securityReadinessMarkdown).toContain("## Scanner Targets");
    expect(securityReadinessMarkdown).toContain("## Action Queue");
    const contextPackText = await fs.readFile(path.join(result.session.outputPaths.analysis, "context-pack-report.json"), "utf8");
    expect(contextPackText).toContain("Repomix token counting git-aware ignore AI-friendly context pack");
    expect(contextPackText).toContain("\"budgetProfiles\"");
    expect(contextPackText).toContain("\"directoryTokenTree\"");
    expect(contextPackText).toContain("\"splitPlans\"");
    expect(contextPackText).toContain("google-ai-studio-1mb");
    const contextPackHtml = await fs.readFile(path.join(result.session.outputPaths.html, "context-pack.html"), "utf8");
    expect(contextPackHtml).toContain("Context Pack");
    expect(contextPackHtml).toContain("context-pack-card");
    expect(contextPackHtml).toContain("context-pack-source-link");
    expect(contextPackHtml).toContain("data-source-pattern=\"Repomix\"");
    expect(contextPackHtml).toContain("Split Output Plan");
    const contextPackMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "context-pack.md"), "utf8");
    expect(contextPackMarkdown).toContain("# Context Pack");
    expect(contextPackMarkdown).toContain("Source pattern: Repomix");
    expect(contextPackMarkdown).toContain("## Split Output Plan");
    const mcpHandoffText = await fs.readFile(path.join(result.session.outputPaths.analysis, "mcp-handoff-report.json"), "utf8");
    expect(mcpHandoffText).toContain("Codebase MCP getCodebase getRemoteCodebase saveCodebase tool handoff");
    expect(mcpHandoffText).toContain("\"getCodebase\"");
    expect(mcpHandoffText).toContain("\"getRemoteCodebase\"");
    expect(mcpHandoffText).toContain("\"saveCodebase\"");
    const mcpHandoffHtml = await fs.readFile(path.join(result.session.outputPaths.html, "mcp-handoff.html"), "utf8");
    expect(mcpHandoffHtml).toContain("MCP Handoff");
    expect(mcpHandoffHtml).toContain("mcp-handoff-card");
    expect(mcpHandoffHtml).toContain("data-source-pattern=\"codebase-mcp\"");
    const mcpHandoffMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "mcp-handoff.md"), "utf8");
    expect(mcpHandoffMarkdown).toContain("# MCP Handoff");
    expect(mcpHandoffMarkdown).toContain("Source pattern: Codebase MCP");
    const agentMemoryText = await fs.readFile(path.join(result.session.outputPaths.analysis, "agent-memory-report.json"), "utf8");
    expect(agentMemoryText).toContain("Claude Code Obsidian Graphify persistent memory token-saving context navigation");
    expect(agentMemoryText).toContain("\"tokenSavings\"");
    expect(agentMemoryText).toContain("\"memoryNotes\"");
    expect(agentMemoryText).toContain("project-context");
    const agentMemoryHtml = await fs.readFile(path.join(result.session.outputPaths.html, "agent-memory.html"), "utf8");
    expect(agentMemoryHtml).toContain("Agent Memory");
    expect(agentMemoryHtml).toContain("agent-memory-card");
    expect(agentMemoryHtml).toContain("data-source-pattern=\"Obsidian Graphify\"");
    expect(agentMemoryHtml).toContain("estimated reduction");
    const agentMemoryMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "agent-memory.md"), "utf8");
    expect(agentMemoryMarkdown).toContain("# Agent Memory");
    expect(agentMemoryMarkdown).toContain("Source pattern: Claude Code Obsidian Graphify");
    expect(agentMemoryMarkdown).toContain("## Context Navigation Rules");
    const graphQueryText = await fs.readFile(path.join(result.session.outputPaths.analysis, "graph-query-report.json"), "utf8");
    expect(graphQueryText).toContain("Graphify query path explain graph traversal command guide");
    expect(graphQueryText).toContain("\"queryModes\"");
    expect(graphQueryText).toContain("\"nodeExplanations\"");
    expect(graphQueryText).toContain("\"pathPrompts\"");
    const graphQueryHtml = await fs.readFile(path.join(result.session.outputPaths.html, "graph-query.html"), "utf8");
    expect(graphQueryHtml).toContain("Graph Query");
    expect(graphQueryHtml).toContain("graph-query-card");
    expect(graphQueryHtml).toContain("data-source-pattern=\"Graphify\"");
    expect(graphQueryHtml).toContain("graphify explain");
    const graphQueryMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "graph-query.md"), "utf8");
    expect(graphQueryMarkdown).toContain("# Graph Query");
    expect(graphQueryMarkdown).toContain("Source pattern: Graphify");
    expect(graphQueryMarkdown).toContain("## Path Prompts");
    const tutorialAbstractionText = await fs.readFile(path.join(result.session.outputPaths.analysis, "tutorial-abstraction-report.json"), "utf8");
    expect(tutorialAbstractionText).toContain("PocketFlow codebase tutorial identify abstractions analyze relationships order chapters");
    expect(tutorialAbstractionText).toContain("\"abstractions\"");
    expect(tutorialAbstractionText).toContain("\"relationships\"");
    expect(tutorialAbstractionText).toContain("\"chapterOrder\"");
    const tutorialAbstractionHtml = await fs.readFile(path.join(result.session.outputPaths.html, "tutorial-abstractions.html"), "utf8");
    expect(tutorialAbstractionHtml).toContain("Tutorial Abstractions");
    expect(tutorialAbstractionHtml).toContain("tutorial-abstraction-card");
    expect(tutorialAbstractionHtml).toContain("data-source-pattern=\"PocketFlow\"");
    expect(tutorialAbstractionHtml).toContain("Chapter Order");
    const tutorialAbstractionMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "tutorial-abstractions.md"), "utf8");
    expect(tutorialAbstractionMarkdown).toContain("# Tutorial Abstractions");
    expect(tutorialAbstractionMarkdown).toContain("Source pattern: PocketFlow");
    expect(tutorialAbstractionMarkdown).toContain("## Chapter Order");
    const decisionRecordText = await fs.readFile(path.join(result.session.outputPaths.analysis, "decision-record-report.json"), "utf8");
    expect(decisionRecordText).toContain("Log4brains ADR docs-as-code status context decision consequences timeline package-specific records");
    expect(decisionRecordText).toContain("\"records\"");
    expect(decisionRecordText).toContain("\"statusCounts\"");
    expect(decisionRecordText).toContain("\"timeline\"");
    expect(decisionRecordText).toContain("\"packageScopes\"");
    const decisionRecordsHtml = await fs.readFile(path.join(result.session.outputPaths.html, "decision-records.html"), "utf8");
    expect(decisionRecordsHtml).toContain("Decision Records");
    expect(decisionRecordsHtml).toContain("decision-record-card");
    expect(decisionRecordsHtml).toContain("data-source-pattern=\"Log4brains\"");
    expect(decisionRecordsHtml).toContain("Positive Consequences");
    const decisionRecordsMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "decision-records.md"), "utf8");
    expect(decisionRecordsMarkdown).toContain("# Decision Records");
    expect(decisionRecordsMarkdown).toContain("Source pattern: Log4brains");
    expect(decisionRecordsMarkdown).toContain("## Timeline");
    const dependencyHealthText = await fs.readFile(path.join(result.session.outputPaths.analysis, "dependency-health-report.json"), "utf8");
    expect(dependencyHealthText).toContain("dependency-cruiser no-circular no-orphans forbidden rules dependency graph validation");
    expect(dependencyHealthText).toContain("\"localDependencyEdges\"");
    expect(dependencyHealthText).toContain("\"cycles\"");
    expect(dependencyHealthText).toContain("\"orphanModules\"");
    expect(dependencyHealthText).toContain("\"ruleViolations\"");
    const dependencyHealthHtml = await fs.readFile(path.join(result.session.outputPaths.html, "dependency-health.html"), "utf8");
    expect(dependencyHealthHtml).toContain("Dependency Health");
    expect(dependencyHealthHtml).toContain("dependency-health-card");
    expect(dependencyHealthHtml).toContain("data-source-pattern=\"dependency-cruiser\"");
    expect(dependencyHealthHtml).toContain("no-circular");
    expect(dependencyHealthHtml).toContain("no-orphans");
    const dependencyHealthMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "dependency-health.md"), "utf8");
    expect(dependencyHealthMarkdown).toContain("# Dependency Health");
    expect(dependencyHealthMarkdown).toContain("Source pattern: dependency-cruiser");
    expect(dependencyHealthMarkdown).toContain("## Rule Violations");
    const exportManifestText = await fs.readFile(path.join(result.session.outputPaths.html, "manifest.json"), "utf8");
    expect(exportManifestText).toContain("\"entrypoints\"");
    expect(exportManifestText).toContain("html/learning-path.html");
    expect(exportManifestText).toContain("html/quiz-print.html");
    expect(exportManifestText).toContain("html/suggested-reads.html");
    expect(exportManifestText).toContain("html/runtime-environment.html");
    expect(exportManifestText).toContain("html/interface-map.html");
    expect(exportManifestText).toContain("html/symbol-map.html");
    expect(exportManifestText).toContain("html/api-reference.html");
    expect(exportManifestText).toContain("html/search-index.html");
    expect(exportManifestText).toContain("html/learning-journal.html");
    expect(exportManifestText).toContain("html/project-activity.html");
    expect(exportManifestText).toContain("html/license-rights.html");
    expect(exportManifestText).toContain("html/sbom.html");
    expect(exportManifestText).toContain("html/security-readiness.html");
    expect(exportManifestText).toContain("html/context-pack.html");
    expect(exportManifestText).toContain("html/mcp-handoff.html");
    expect(exportManifestText).toContain("html/agent-memory.html");
    expect(exportManifestText).toContain("html/graph-query.html");
    expect(exportManifestText).toContain("html/tutorial-abstractions.html");
    expect(exportManifestText).toContain("html/decision-records.html");
    expect(exportManifestText).toContain("html/dependency-health.html");
    expect(exportManifestText).toContain("\"integrity\"");
    expect(exportManifestText).toContain("\"bytes\"");
    expect(exportManifestText).toContain("\"sha256\"");
    expect(exportManifestText).toContain("\"readmePath\"");
    expect(exportManifestText).toContain("assets/component-graph.mmd");
    expect(exportManifestText).toContain("assets/learning-path.tour.json");
    expect(exportManifestText).toContain("assets/search-index.json");
    expect(exportManifestText).toContain("assets/learning-journal-template.md");
    const exportReadmeText = await fs.readFile(path.join(result.session.outputPaths.html, "EXPORT-README.md"), "utf8");
    expect(exportReadmeText).toContain("RepoTutor HTML Export");
    expect(exportReadmeText).toContain("Entry Points");
    expect(exportReadmeText).toContain("Integrity metadata uses sha256");
    expect(exportReadmeText).toContain("assets/component-graph.mmd");
    expect(exportReadmeText).toContain("assets/learning-path.tour.json");
    expect(exportReadmeText).toContain("assets/search-index.json");
    expect(exportReadmeText).toContain("assets/learning-journal-template.md");
    const filesHtml = await fs.readFile(path.join(result.session.outputPaths.html, "files.html"), "utf8");
    expect(filesHtml).toContain("file-nav-toolbar");
    expect(filesHtml).toContain("data-file-ext-filter");
    expect(filesHtml).toContain("data-file-dir-filter");
    expect(filesHtml).toContain("data-file-dir");
    expect(filesHtml).toContain("data-source-evidence-filter");
    expect(filesHtml).toContain("data-source-evidence");
    expect(filesHtml).toContain("근거 있음");
    expect(filesHtml).toContain("소스 근거");
    expect(filesHtml).toContain("source-evidence");
    expect(filesHtml).toContain("source-link");
    expect(filesHtml).toContain("원본 열기");
    expect(filesHtml).toContain("../source/src/main.ts");
    expect(filesHtml).toContain("import { createGreeting }");
    const filesMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "files.md"), "utf8");
    expect(filesMarkdown).toContain("### 소스 근거");
    expect(filesMarkdown).toContain("[원본](../source/src/main.ts)");
    const evidenceMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "evidence.md"), "utf8");
    expect(evidenceMarkdown).toContain("# 소스 근거 인덱스");
    expect(evidenceMarkdown).toContain("[src/main.ts](files.md#src-main-ts)");
    const evidenceHtml = await fs.readFile(path.join(result.session.outputPaths.html, "evidence.html"), "utf8");
    expect(evidenceHtml).toContain("소스 근거 인덱스");
    expect(evidenceHtml).toContain("evidence-index-cards");
    expect(evidenceHtml).toContain("evidence-kind-toolbar");
    expect(evidenceHtml).toContain("data-evidence-kind-filter");
    expect(evidenceHtml).toContain("data-evidence-kind=\"import\"");
    expect(evidenceHtml).toContain("files.html#src-main.ts");
    expect(evidenceHtml).toContain("../source/src/main.ts");
    const learningPathHtml = await fs.readFile(path.join(result.session.outputPaths.html, "learning-path.html"), "utf8");
    expect(learningPathHtml).toContain("학습 경로");
    expect(learningPathHtml).toContain("learning-path-step");
    expect(learningPathHtml).toContain("data-learning-primary");
    expect(learningPathHtml).toContain("기본 투어");
    expect(learningPathHtml).toContain("id=\"learning-step-1\"");
    expect(learningPathHtml).toContain("learning-step-nav");
    expect(learningPathHtml).toContain("href=\"#learning-step-2\"");
    expect(learningPathHtml).toContain("다음 단계");
    expect(learningPathHtml).toContain("이전 단계");
    expect(learningPathHtml).toContain("data-learning-step");
    expect(learningPathHtml).toContain("data-learning-step-complete");
    expect(learningPathHtml).toContain("data-reset-learning-progress");
    expect(learningPathHtml).toContain("data-learning-progress-summary");
    expect(learningPathHtml).toContain("완료 0 /");
    expect(learningPathHtml).toContain("진도 초기화");
    expect(learningPathHtml).toContain("학습 완료");
    expect(learningPathHtml).toContain("data-source-pattern=\"CodeTour\"");
    expect(learningPathHtml).toContain("component-graph.html");
    expect(learningPathHtml).toContain("runtime-environment.html");
    expect(learningPathHtml).toContain("interface-map.html");
    expect(learningPathHtml).toContain("symbol-map.html");
    expect(learningPathHtml).toContain("api-reference.html");
    expect(learningPathHtml).toContain("search-index.html");
    expect(learningPathHtml).toContain("learning-journal.html");
    expect(learningPathHtml).toContain("project-activity.html");
    expect(learningPathHtml).toContain("license-rights.html");
    expect(learningPathHtml).toContain("sbom.html");
    expect(learningPathHtml).toContain("security-readiness.html");
    expect(learningPathHtml).toContain("context-pack.html");
    expect(learningPathHtml).toContain("mcp-handoff.html");
    expect(learningPathHtml).toContain("agent-memory.html");
    expect(learningPathHtml).toContain("graph-query.html");
    expect(learningPathHtml).toContain("tutorial-abstractions.html");
    expect(learningPathHtml).toContain("decision-records.html");
    expect(learningPathHtml).toContain("dependency-health.html");
    const sessionVerificationHtml = await fs.readFile(path.join(result.session.outputPaths.html, "session-verification.html"), "utf8");
    expect(sessionVerificationHtml).toContain("세션 검증");
    expect(sessionVerificationHtml).toContain("../analysis/session-verification-report.json");
    expect(sessionVerificationHtml).toContain("../markdown/session-verification.md");
    expect(sessionVerificationHtml).toContain("repo-tutor verify-session");
    const quizPrintHtml = await fs.readFile(path.join(result.session.outputPaths.html, "quiz-print.html"), "utf8");
    expect(quizPrintHtml).toContain("퀴즈 정답지");
    expect(quizPrintHtml).toContain("print-answer-key");
    expect(quizPrintHtml).toContain("<strong>정답:</strong>");
    expect(quizPrintHtml).toContain("<strong>해설:</strong>");
    const quizHtml = await fs.readFile(path.join(result.session.outputPaths.html, "quiz.html"), "utf8");
    expect(quizHtml).toContain("quiz-reset-toolbar");
    expect(quizHtml).toContain("data-reset-quiz");
    expect(quizHtml).toContain("복습 초기화");
    expect(quizHtml).toContain("quiz-section-toolbar");
    expect(quizHtml).toContain("data-quiz-section-filter");
    expect(quizHtml).toContain("data-quiz-difficulty-filter");
    expect(quizHtml).toContain("data-quiz-section");
    expect(quizHtml).toContain("data-quiz-difficulty");
    const appJs = await fs.readFile(path.join(result.session.outputPaths.html, "assets", "app.js"), "utf8");
    expect(appJs).toContain("[data-evidence-kind-filter]");
    expect(appJs).toContain("[data-quiz-section-filter]");
    expect(appJs).toContain("repotutor:learning-path");
    expect(appJs).toContain("learningProgress");
    expect(appJs).toContain("[data-reset-learning-progress]");
    expect(appJs).toContain("learningProgress.clear()");
    expect(appJs).toContain("[data-learning-progress-summary]");
    expect(appJs).toContain("updateLearningProgressSummary");
    expect(appJs).toContain("localStorage");
    expect(appJs).toContain("[data-reset-quiz]");
    expect(appJs).toContain("picked.clear()");
    expect(appJs).toContain("[data-download-mermaid]");
    const fileLessonsText = await fs.readFile(path.join(result.session.outputPaths.analysis, "file-lessons.json"), "utf8");
    expect(fileLessonsText).toContain("\"sourceEvidence\"");
    expect(fileLessonsText).toContain("\"snippet\"");
    const evidenceIndexText = await fs.readFile(path.join(result.session.outputPaths.analysis, "evidence-index-report.json"), "utf8");
    expect(evidenceIndexText).toContain("\"totalEvidenceItems\"");
    expect(evidenceIndexText).toContain("\"evidenceByKind\"");
    expect(evidenceIndexText).toContain("\"lessonHref\"");
    expect(evidenceIndexText).toContain("\"sourceHref\"");
    expect(evidenceIndexText).toContain("html/files.html#src-main.ts");
    expect(evidenceIndexText).toContain("source/src/main.ts");
    const sessionVerificationText = await fs.readFile(path.join(result.session.outputPaths.analysis, "session-verification-report.json"), "utf8");
    expect(sessionVerificationText).toContain("\"ok\": true");
    expect(sessionVerificationText).toContain("\"checkedRequiredArtifacts\"");
    expect(sessionVerificationText).toContain("\"evidenceIndex\"");
    const sessionVerificationMarkdown = await fs.readFile(path.join(result.session.outputPaths.markdown, "session-verification.md"), "utf8");
    expect(sessionVerificationMarkdown).toContain("# 세션 검증");
    expect(sessionVerificationMarkdown).toContain("상태: PASS");
    expect(sessionVerificationMarkdown).toContain("evidenceIndex: PASS");
    const evidenceVerification = await verifyEvidenceIndexReport(result.session.outputPaths.root);
    expect(evidenceVerification.ok).toBe(true);
    expect(evidenceVerification.checkedItems).toBeGreaterThan(0);
    expect(evidenceVerification.checkedSourceFiles).toBeGreaterThan(0);
    expect(evidenceVerification.checkedSourceLinks).toBeGreaterThan(0);
    expect(evidenceVerification.checkedLessonLinks).toBeGreaterThan(0);
    expect(evidenceVerification.failures).toHaveLength(0);
    const zip = await writeHtmlZipBundle(result.session.outputPaths.root);
    expect(zip.fileCount).toBeGreaterThan(5);
    expect(zip.bytes).toBeGreaterThan(100);
    const zipSignature = await fs.readFile(zip.zipPath).then((buffer) => buffer.subarray(0, 4).toString("hex"));
    expect(zipSignature).toBe("504b0304");
    const zipText = await fs.readFile(zip.zipPath, "latin1");
    expect(zipText).toContain("assets/component-graph.mmd");
    expect(zipText).toContain("assets/learning-path.tour.json");
    expect(zipText).toContain("assets/search-index.json");
    expect(zipText).toContain("assets/learning-journal-template.md");
    const exportVerification = await verifyHtmlExportManifest(result.session.outputPaths.root);
    expect(exportVerification.ok).toBe(true);
    expect(exportVerification.checkedFiles).toBeGreaterThan(5);
    expect(exportVerification.failures).toHaveLength(0);
    const sessionVerification = await verifyStudySessionArtifacts(result.session.outputPaths.root);
    expect(sessionVerification.ok).toBe(true);
    expect(sessionVerification.checks.session).toBe(true);
    expect(sessionVerification.checks.requiredArtifacts).toBe(true);
    expect(sessionVerification.checks.htmlExport).toBe(true);
    expect(sessionVerification.checks.evidenceIndex).toBe(true);
    expect(sessionVerification.checkedRequiredArtifacts).toBeGreaterThan(5);
    expect(sessionVerification.failures).toHaveLength(0);
    await fs.appendFile(path.join(result.session.outputPaths.html, "index.html"), "\n<!-- tampered -->\n");
    const tamperedVerification = await verifyHtmlExportManifest(result.session.outputPaths.root);
    expect(tamperedVerification.ok).toBe(false);
    expect(tamperedVerification.failures[0]?.path).toBe("html/index.html");
    await fs.rm(path.join(result.session.outputPaths.source, "src", "main.ts"));
    const missingSourceVerification = await verifyEvidenceIndexReport(result.session.outputPaths.root);
    expect(missingSourceVerification.ok).toBe(false);
    expect(missingSourceVerification.failures.some((failure) => failure.reason === "missing-source-path" && failure.path === "source/src/main.ts")).toBe(true);
    const failedSessionVerification = await verifyStudySessionArtifacts(result.session.outputPaths.root);
    expect(failedSessionVerification.ok).toBe(false);
    expect(failedSessionVerification.checks.htmlExport).toBe(false);
    expect(failedSessionVerification.checks.evidenceIndex).toBe(false);
    expect(failedSessionVerification.failures.some((failure) => failure.check === "html-export" && failure.path === "html/index.html")).toBe(true);
    expect(failedSessionVerification.failures.some((failure) => failure.check === "evidence-index" && failure.path === "source/src/main.ts")).toBe(true);
    const quizText = await fs.readFile(path.join(result.session.outputPaths.analysis, "quiz.json"), "utf8");
    expect(quizText).toContain("\"choices\"");
  });

  it("compares a new study session against the previous source snapshot", async () => {
    const studiesRoot = await fs.mkdtemp(path.join(os.tmpdir(), "repotutor-incremental-studies-"));
    const sourceRoot = await fs.mkdtemp(path.join(os.tmpdir(), "repotutor-incremental-source-"));
    await fs.cp(fixtureRoot, sourceRoot, { recursive: true });
    await fs.writeFile(path.join(sourceRoot, "scratch.txt"), "temporary notes not important to the lesson map\n");

    const first = await runStudy({ source: sourceRoot, mode: "quick", level: "beginner", studiesRoot });
    await fs.writeFile(path.join(sourceRoot, "src", "added.ts"), "export const added = 'next lesson';\n");
    await fs.appendFile(path.join(sourceRoot, "src", "message.ts"), "\nexport const changed = true;\n");
    await fs.rm(path.join(sourceRoot, "README.md"));
    await fs.rm(path.join(sourceRoot, "scratch.txt"));

    const second = await runStudy({ source: sourceRoot, mode: "quick", level: "beginner", studiesRoot });

    expect(second.analysis.incrementalReport.baselineSessionId).toBe(first.session.sessionId);
    expect(second.analysis.incrementalReport.addedFiles).toContain("src/added.ts");
    expect(second.analysis.incrementalReport.changedFiles).toContain("src/message.ts");
    expect(second.analysis.incrementalReport.removedFiles).toContain("README.md");
    expect(second.analysis.incrementalReport.unchangedFiles).toContain("src/main.ts");
    expect(second.analysis.incrementalReport.coverageDelta.baselineCoverageRatio).toBeLessThan(second.analysis.incrementalReport.coverageDelta.currentCoverageRatio);
    expect(second.analysis.incrementalReport.coverageDelta.coverageRatioDelta).toBeGreaterThan(0);
  });

  it("resolves relative local sources against an explicit source base directory", async () => {
    const studiesRoot = await fs.mkdtemp(path.join(os.tmpdir(), "repotutor-relative-studies-"));
    const sourceBaseDir = await fs.mkdtemp(path.join(os.tmpdir(), "repotutor-relative-source-base-"));
    await fs.cp(fixtureRoot, path.join(sourceBaseDir, "relative-app"), { recursive: true });

    const result = await runStudy({
      source: "relative-app",
      sourceBaseDir,
      mode: "quick",
      level: "beginner",
      studiesRoot
    });

    expect(result.session.status).toBe("complete");
    expect(result.session.localSourcePath).toBe(path.join(sourceBaseDir, "relative-app"));
    await expect(fs.access(path.join(result.session.outputPaths.html, "index.html"))).resolves.toBeUndefined();
  });

  it("uses the required quiz count formula bounds", () => {
    expect(calculateQuizCount({ mode: "quick", folderCount: 1, fileCount: 1, glossaryCount: 1, sectionCount: 1 })).toBeGreaterThanOrEqual(5);
    expect(calculateQuizCount({ mode: "standard", folderCount: 100, fileCount: 100, glossaryCount: 100, sectionCount: 12 })).toBeLessThanOrEqual(35);
    expect(calculateQuizCount({ mode: "deep", folderCount: 100, fileCount: 100, glossaryCount: 100, sectionCount: 12 })).toBeLessThanOrEqual(60);
  });
});
