import fs from "node:fs/promises";
import path from "node:path";
import { StudySessionSchema, type StudySession } from "@repotutor/shared";
import { verifyEvidenceIndexReport, type EvidenceVerificationResult } from "./evidence.js";
import { verifyHtmlExportManifest, type HtmlExportVerificationResult } from "./exporter.js";
import { TEACHING_WORKSPACE_REQUIRED_ARTIFACTS } from "./teaching-workspace.js";

export type StudySessionVerificationReason =
  | "missing-session"
  | "invalid-session"
  | "incomplete-session"
  | "missing-artifact"
  | "html-export-error"
  | "html-export-failed"
  | "evidence-index-failed";

export interface StudySessionVerificationFailure {
  check: "session" | "required-artifacts" | "html-export" | "evidence-index";
  reason: StudySessionVerificationReason;
  path: string;
  detail?: string;
}

export interface StudySessionVerificationResult {
  ok: boolean;
  sessionRoot: string;
  sessionId: string | null;
  checkedRequiredArtifacts: number;
  checks: {
    session: boolean;
    requiredArtifacts: boolean;
    htmlExport: boolean;
    evidenceIndex: boolean;
  };
  htmlExport: HtmlExportVerificationResult | null;
  evidenceIndex: EvidenceVerificationResult | null;
  failures: StudySessionVerificationFailure[];
}

const REQUIRED_ARTIFACTS = [
  "session.json",
  ...TEACHING_WORKSPACE_REQUIRED_ARTIFACTS,
  "analysis/repo-map.json",
  "analysis/file-lessons.json",
  "analysis/evidence-index-report.json",
  "analysis/suggested-reads-report.json",
  "analysis/runtime-environment-report.json",
  "analysis/interface-map-report.json",
  "analysis/symbol-map-report.json",
  "analysis/api-reference-report.json",
  "analysis/search-index-report.json",
  "analysis/learning-journal-report.json",
  "analysis/daily-summary-report.json",
  "analysis/vibe-coding-prompt-pack-report.json",
  "analysis/project-activity-report.json",
  "analysis/code-metrics-readiness-report.json",
  "analysis/code-ownership-readiness-report.json",
  "analysis/large-asset-readiness-report.json",
  "analysis/license-rights-report.json",
  "analysis/sbom-report.json",
  "analysis/security-readiness-report.json",
  "analysis/sast-readiness-report.json",
  "analysis/dast-readiness-report.json",
  "analysis/threat-model-readiness-report.json",
  "analysis/scorecard-report.json",
  "analysis/provenance-report.json",
  "analysis/advisory-report.json",
  "analysis/vex-report.json",
  "analysis/policy-gate-report.json",
  "analysis/api-contract-report.json",
  "analysis/consumer-contract-readiness-report.json",
  "analysis/observability-report.json",
  "analysis/performance-report.json",
  "analysis/profiling-readiness-report.json",
  "analysis/tracing-readiness-report.json",
  "analysis/debug-readiness-report.json",
  "analysis/crash-reporting-readiness-report.json",
  "analysis/incident-response-readiness-report.json",
  "analysis/slo-readiness-report.json",
  "analysis/cost-readiness-report.json",
  "analysis/progressive-delivery-readiness-report.json",
  "analysis/load-testing-readiness-report.json",
  "analysis/benchmark-readiness-report.json",
  "analysis/e2e-report.json",
  "analysis/flaky-test-readiness-report.json",
  "analysis/test-impact-readiness-report.json",
  "analysis/test-reporting-readiness-report.json",
  "analysis/snapshot-readiness-report.json",
  "analysis/property-based-testing-readiness-report.json",
  "analysis/fuzz-readiness-report.json",
  "analysis/test-data-readiness-report.json",
  "analysis/integration-test-environment-readiness-report.json",
  "analysis/chaos-engineering-readiness-report.json",
  "analysis/accessibility-report.json",
  "analysis/storybook-report.json",
  "analysis/design-tokens-report.json",
  "analysis/i18n-report.json",
  "analysis/release-readiness-report.json",
  "analysis/secret-readiness-report.json",
  "analysis/secret-management-readiness-report.json",
  "analysis/container-readiness-report.json",
  "analysis/container-scan-readiness-report.json",
  "analysis/code-quality-report.json",
  "analysis/documentation-report.json",
  "analysis/database-readiness-report.json",
  "analysis/database-migration-readiness-report.json",
  "analysis/database-orm-readiness-report.json",
  "analysis/data-transformation-readiness-report.json",
  "analysis/data-quality-readiness-report.json",
  "analysis/data-lineage-readiness-report.json",
  "analysis/data-catalog-readiness-report.json",
  "analysis/data-annotation-readiness-report.json",
  "analysis/lakehouse-table-readiness-report.json",
  "analysis/feature-store-readiness-report.json",
  "analysis/model-registry-readiness-report.json",
  "analysis/experiment-tracking-readiness-report.json",
  "analysis/model-monitoring-readiness-report.json",
  "analysis/model-serving-readiness-report.json",
  "analysis/model-training-readiness-report.json",
  "analysis/ci-cd-report.json",
  "analysis/unit-test-report.json",
  "analysis/coverage-readiness-report.json",
  "analysis/mutation-testing-readiness-report.json",
  "analysis/typecheck-readiness-report.json",
  "analysis/package-manager-report.json",
  "analysis/git-hooks-report.json",
  "analysis/task-runner-report.json",
  "analysis/dependency-update-report.json",
  "analysis/dependency-review-readiness-report.json",
  "analysis/lint-readiness-report.json",
  "analysis/format-readiness-report.json",
  "analysis/commit-conventions-report.json",
  "analysis/changelog-readiness-report.json",
  "analysis/bundle-analysis-report.json",
  "analysis/mocking-readiness-report.json",
  "analysis/data-fetching-readiness-report.json",
  "analysis/routing-readiness-report.json",
  "analysis/state-management-readiness-report.json",
  "analysis/form-readiness-report.json",
  "analysis/auth-readiness-report.json",
  "analysis/authorization-readiness-report.json",
  "analysis/payment-readiness-report.json",
  "analysis/email-readiness-report.json",
  "analysis/queue-readiness-report.json",
  "analysis/event-stream-readiness-report.json",
  "analysis/data-connector-readiness-report.json",
  "analysis/semantic-layer-readiness-report.json",
  "analysis/bi-dashboard-readiness-report.json",
  "analysis/schema-registry-readiness-report.json",
  "analysis/stream-processing-readiness-report.json",
  "analysis/pipeline-orchestration-readiness-report.json",
  "analysis/service-mesh-readiness-report.json",
  "analysis/ingress-controller-readiness-report.json",
  "analysis/dns-readiness-report.json",
  "analysis/certificate-readiness-report.json",
  "analysis/helm-readiness-report.json",
  "analysis/admission-policy-readiness-report.json",
  "analysis/api-gateway-readiness-report.json",
  "analysis/cache-readiness-report.json",
  "analysis/logging-readiness-report.json",
  "analysis/feature-flag-readiness-report.json",
  "analysis/rate-limit-readiness-report.json",
  "analysis/error-tracking-readiness-report.json",
  "analysis/analytics-readiness-report.json",
  "analysis/http-client-readiness-report.json",
  "analysis/schema-validation-readiness-report.json",
  "analysis/datetime-readiness-report.json",
  "analysis/id-generation-readiness-report.json",
  "analysis/image-processing-readiness-report.json",
  "analysis/file-upload-readiness-report.json",
  "analysis/websocket-readiness-report.json",
  "analysis/realtime-media-readiness-report.json",
  "analysis/pdf-generation-readiness-report.json",
  "analysis/spreadsheet-readiness-report.json",
  "analysis/chart-visualization-readiness-report.json",
  "analysis/markdown-code-rendering-readiness-report.json",
  "analysis/notebook-readiness-report.json",
  "analysis/map-visualization-readiness-report.json",
  "analysis/diagram-rendering-readiness-report.json",
  "analysis/link-integrity-readiness-report.json",
  "analysis/seo-metadata-readiness-report.json",
  "analysis/pwa-readiness-report.json",
  "analysis/browser-compat-readiness-report.json",
  "analysis/browser-extension-readiness-report.json",
  "analysis/env-validation-readiness-report.json",
  "analysis/security-headers-readiness-report.json",
  "analysis/graphql-readiness-report.json",
  "analysis/cli-readiness-report.json",
  "analysis/terminal-ui-readiness-report.json",
  "analysis/state-machine-readiness-report.json",
  "analysis/animation-readiness-report.json",
  "analysis/drag-and-drop-readiness-report.json",
  "analysis/rich-text-editor-readiness-report.json",
  "analysis/command-palette-readiness-report.json",
  "analysis/guided-tour-readiness-report.json",
  "analysis/data-table-readiness-report.json",
  "analysis/calendar-readiness-report.json",
  "analysis/dialog-readiness-report.json",
  "analysis/popover-tooltip-readiness-report.json",
  "analysis/menu-dropdown-readiness-report.json",
  "analysis/toast-snackbar-readiness-report.json",
  "analysis/tabs-accordion-readiness-report.json",
  "analysis/checkbox-radio-switch-readiness-report.json",
  "analysis/slider-progress-readiness-report.json",
  "analysis/select-combobox-readiness-report.json",
  "analysis/toolbar-toggle-readiness-report.json",
  "analysis/scroll-area-readiness-report.json",
  "analysis/avatar-readiness-report.json",
  "analysis/pin-input-readiness-report.json",
  "analysis/pagination-readiness-report.json",
  "analysis/number-input-readiness-report.json",
  "analysis/rating-group-readiness-report.json",
  "analysis/color-picker-readiness-report.json",
  "analysis/splitter-readiness-report.json",
  "analysis/tags-input-readiness-report.json",
  "analysis/clipboard-readiness-report.json",
  "analysis/qr-code-readiness-report.json",
  "analysis/timer-readiness-report.json",
  "analysis/steps-readiness-report.json",
  "analysis/carousel-readiness-report.json",
  "analysis/tree-view-readiness-report.json",
  "analysis/collapsible-readiness-report.json",
  "analysis/editable-readiness-report.json",
  "analysis/password-input-readiness-report.json",
  "analysis/signature-pad-readiness-report.json",
  "analysis/angle-slider-readiness-report.json",
  "analysis/cascade-select-readiness-report.json",
  "analysis/async-list-readiness-report.json",
  "analysis/image-cropper-readiness-report.json",
  "analysis/listbox-readiness-report.json",
  "analysis/date-picker-readiness-report.json",
  "analysis/marquee-readiness-report.json",
  "analysis/toc-readiness-report.json",
  "analysis/floating-panel-readiness-report.json",
  "analysis/drawer-readiness-report.json",
  "analysis/hover-card-readiness-report.json",
  "analysis/navigation-menu-readiness-report.json",
  "analysis/presence-readiness-report.json",
  "analysis/menu-readiness-report.json",
  "analysis/tooltip-readiness-report.json",
  "analysis/llm-readiness-report.json",
  "analysis/llm-eval-readiness-report.json",
  "analysis/llm-observability-readiness-report.json",
  "analysis/vector-db-readiness-report.json",
  "analysis/search-service-readiness-report.json",
  "analysis/object-storage-readiness-report.json",
  "analysis/realtime-collaboration-readiness-report.json",
  "analysis/workflow-orchestration-readiness-report.json",
  "analysis/openapi-client-readiness-report.json",
  "analysis/webhook-readiness-report.json",
  "analysis/notification-readiness-report.json",
  "analysis/consent-readiness-report.json",
  "analysis/privacy-readiness-report.json",
  "analysis/server-framework-readiness-report.json",
  "analysis/rpc-readiness-report.json",
  "analysis/workspace-graph-readiness-report.json",
  "analysis/scaffolding-readiness-report.json",
  "analysis/scheduler-readiness-report.json",
  "analysis/build-tool-readiness-report.json",
  "analysis/styling-readiness-report.json",
  "analysis/visual-regression-readiness-report.json",
  "analysis/infrastructure-readiness-report.json",
  "analysis/iac-drift-readiness-report.json",
  "analysis/deployment-readiness-report.json",
  "analysis/serverless-readiness-report.json",
  "analysis/mobile-readiness-report.json",
  "analysis/desktop-readiness-report.json",
  "analysis/edge-readiness-report.json",
  "analysis/compose-readiness-report.json",
  "analysis/devcontainer-readiness-report.json",
  "analysis/kubernetes-readiness-report.json",
  "analysis/gitops-readiness-report.json",
  "analysis/backup-readiness-report.json",
  "analysis/context-pack-report.json",
  "analysis/mcp-handoff-report.json",
  "analysis/agent-memory-report.json",
  "analysis/graph-query-report.json",
  "analysis/tutorial-abstraction-report.json",
  "analysis/decision-record-report.json",
  "analysis/dependency-health-report.json",
  "markdown/overview.md",
  "markdown/evidence.md",
  "markdown/suggested-reads.md",
  "markdown/runtime-environment.md",
  "markdown/interface-map.md",
  "markdown/symbol-map.md",
  "markdown/api-reference.md",
  "markdown/search-index.md",
  "markdown/learning-journal.md",
  "markdown/daily-summary.md",
  "markdown/vibe-coding-prompt-pack.md",
  "markdown/improvement-backlog.md",
  "markdown/project-activity.md",
  "markdown/code-metrics-readiness.md",
  "markdown/code-ownership-readiness.md",
  "markdown/large-asset-readiness.md",
  "markdown/license-rights.md",
  "markdown/sbom.md",
  "markdown/security-readiness.md",
  "markdown/sast-readiness.md",
  "markdown/dast-readiness.md",
  "markdown/threat-model-readiness.md",
  "markdown/scorecard.md",
  "markdown/provenance.md",
  "markdown/advisories.md",
  "markdown/vex.md",
  "markdown/policy-gates.md",
  "markdown/api-contracts.md",
  "markdown/consumer-contract-readiness.md",
  "markdown/observability.md",
  "markdown/performance.md",
  "markdown/profiling-readiness.md",
  "markdown/tracing-readiness.md",
  "markdown/debug-readiness.md",
  "markdown/crash-reporting-readiness.md",
  "markdown/incident-response-readiness.md",
  "markdown/slo-readiness.md",
  "markdown/cost-readiness.md",
  "markdown/progressive-delivery-readiness.md",
  "markdown/load-testing-readiness.md",
  "markdown/benchmark-readiness.md",
  "markdown/e2e.md",
  "markdown/flaky-test-readiness.md",
  "markdown/test-impact-readiness.md",
  "markdown/test-reporting-readiness.md",
  "markdown/snapshot-readiness.md",
  "markdown/property-based-testing-readiness.md",
  "markdown/fuzz-readiness.md",
  "markdown/test-data-readiness.md",
  "markdown/integration-test-environment-readiness.md",
  "markdown/accessibility.md",
  "markdown/storybook.md",
  "markdown/design-tokens.md",
  "markdown/i18n.md",
  "markdown/release-readiness.md",
  "markdown/secret-readiness.md",
  "markdown/secret-management-readiness.md",
  "markdown/container-readiness.md",
  "markdown/container-scan-readiness.md",
  "markdown/code-quality.md",
  "markdown/documentation.md",
  "markdown/database-readiness.md",
  "markdown/database-migration-readiness.md",
  "markdown/database-orm-readiness.md",
  "markdown/data-transformation-readiness.md",
  "markdown/data-quality-readiness.md",
  "markdown/data-lineage-readiness.md",
  "markdown/data-catalog-readiness.md",
  "markdown/data-annotation-readiness.md",
  "markdown/lakehouse-table-readiness.md",
  "markdown/feature-store-readiness.md",
  "markdown/model-registry-readiness.md",
  "markdown/experiment-tracking-readiness.md",
  "markdown/model-monitoring-readiness.md",
  "markdown/model-serving-readiness.md",
  "markdown/model-training-readiness.md",
  "markdown/ci-cd.md",
  "markdown/unit-tests.md",
  "markdown/coverage-readiness.md",
  "markdown/mutation-testing-readiness.md",
  "markdown/typecheck-readiness.md",
  "markdown/package-manager.md",
  "markdown/git-hooks.md",
  "markdown/task-runner.md",
  "markdown/dependency-updates.md",
  "markdown/dependency-review-readiness.md",
  "markdown/lint-readiness.md",
  "markdown/format-readiness.md",
  "markdown/commit-conventions.md",
  "markdown/changelog-readiness.md",
  "markdown/bundle-analysis.md",
  "markdown/mocking-readiness.md",
  "markdown/data-fetching-readiness.md",
  "markdown/routing-readiness.md",
  "markdown/state-management-readiness.md",
  "markdown/form-readiness.md",
  "markdown/auth-readiness.md",
  "markdown/authorization-readiness.md",
  "markdown/payment-readiness.md",
  "markdown/email-readiness.md",
  "markdown/queue-readiness.md",
  "markdown/event-stream-readiness.md",
  "markdown/data-connector-readiness.md",
  "markdown/semantic-layer-readiness.md",
  "markdown/bi-dashboard-readiness.md",
  "markdown/schema-registry-readiness.md",
  "markdown/stream-processing-readiness.md",
  "markdown/pipeline-orchestration-readiness.md",
  "markdown/service-mesh-readiness.md",
  "markdown/ingress-controller-readiness.md",
  "markdown/dns-readiness.md",
  "markdown/certificate-readiness.md",
  "markdown/helm-readiness.md",
  "markdown/admission-policy-readiness.md",
  "markdown/api-gateway-readiness.md",
  "markdown/cache-readiness.md",
  "markdown/logging-readiness.md",
  "markdown/feature-flag-readiness.md",
  "markdown/rate-limit-readiness.md",
  "markdown/error-tracking-readiness.md",
  "markdown/analytics-readiness.md",
  "markdown/http-client-readiness.md",
  "markdown/schema-validation-readiness.md",
  "markdown/datetime-readiness.md",
  "markdown/id-generation-readiness.md",
  "markdown/image-processing-readiness.md",
  "markdown/file-upload-readiness.md",
  "markdown/websocket-readiness.md",
  "markdown/realtime-media-readiness.md",
  "markdown/pdf-generation-readiness.md",
  "markdown/spreadsheet-readiness.md",
  "markdown/chart-visualization-readiness.md",
  "markdown/markdown-code-rendering-readiness.md",
  "markdown/notebook-readiness.md",
  "markdown/map-visualization-readiness.md",
  "markdown/diagram-rendering-readiness.md",
  "markdown/link-integrity-readiness.md",
  "markdown/seo-metadata-readiness.md",
  "markdown/pwa-readiness.md",
  "markdown/browser-compat-readiness.md",
  "markdown/browser-extension-readiness.md",
  "markdown/env-validation-readiness.md",
  "markdown/security-headers-readiness.md",
  "markdown/graphql-readiness.md",
  "markdown/cli-readiness.md",
  "markdown/terminal-ui-readiness.md",
  "markdown/state-machine-readiness.md",
  "markdown/animation-readiness.md",
  "markdown/drag-and-drop-readiness.md",
  "markdown/rich-text-editor-readiness.md",
  "markdown/command-palette-readiness.md",
  "markdown/guided-tour-readiness.md",
  "markdown/data-table-readiness.md",
  "markdown/calendar-readiness.md",
  "markdown/dialog-readiness.md",
  "markdown/popover-tooltip-readiness.md",
  "markdown/menu-dropdown-readiness.md",
  "markdown/toast-snackbar-readiness.md",
  "markdown/tabs-accordion-readiness.md",
  "markdown/checkbox-radio-switch-readiness.md",
  "markdown/slider-progress-readiness.md",
  "markdown/select-combobox-readiness.md",
  "markdown/toolbar-toggle-readiness.md",
  "markdown/scroll-area-readiness.md",
  "markdown/avatar-readiness.md",
  "markdown/pin-input-readiness.md",
  "markdown/pagination-readiness.md",
  "markdown/number-input-readiness.md",
  "markdown/rating-group-readiness.md",
  "markdown/color-picker-readiness.md",
  "markdown/splitter-readiness.md",
  "markdown/tags-input-readiness.md",
  "markdown/clipboard-readiness.md",
  "markdown/qr-code-readiness.md",
  "markdown/timer-readiness.md",
  "markdown/steps-readiness.md",
  "markdown/carousel-readiness.md",
  "markdown/tree-view-readiness.md",
  "markdown/collapsible-readiness.md",
  "markdown/editable-readiness.md",
  "markdown/password-input-readiness.md",
  "markdown/signature-pad-readiness.md",
  "markdown/angle-slider-readiness.md",
  "markdown/cascade-select-readiness.md",
  "markdown/async-list-readiness.md",
  "markdown/image-cropper-readiness.md",
  "markdown/listbox-readiness.md",
  "markdown/date-picker-readiness.md",
  "markdown/marquee-readiness.md",
  "markdown/toc-readiness.md",
  "markdown/floating-panel-readiness.md",
  "markdown/drawer-readiness.md",
  "markdown/hover-card-readiness.md",
  "markdown/navigation-menu-readiness.md",
  "markdown/presence-readiness.md",
  "markdown/menu-readiness.md",
  "markdown/tooltip-readiness.md",
  "markdown/llm-readiness.md",
  "markdown/llm-eval-readiness.md",
  "markdown/llm-observability-readiness.md",
  "markdown/vector-db-readiness.md",
  "markdown/search-service-readiness.md",
  "markdown/object-storage-readiness.md",
  "markdown/realtime-collaboration-readiness.md",
  "markdown/workflow-orchestration-readiness.md",
  "markdown/openapi-client-readiness.md",
  "markdown/webhook-readiness.md",
  "markdown/notification-readiness.md",
  "markdown/consent-readiness.md",
  "markdown/privacy-readiness.md",
  "markdown/server-framework-readiness.md",
  "markdown/rpc-readiness.md",
  "markdown/workspace-graph-readiness.md",
  "markdown/scaffolding-readiness.md",
  "markdown/scheduler-readiness.md",
  "markdown/build-tool-readiness.md",
  "markdown/styling-readiness.md",
  "markdown/visual-regression-readiness.md",
  "markdown/infrastructure-readiness.md",
  "markdown/iac-drift-readiness.md",
  "markdown/deployment-readiness.md",
  "markdown/serverless-readiness.md",
  "markdown/mobile-readiness.md",
  "markdown/desktop-readiness.md",
  "markdown/edge-readiness.md",
  "markdown/compose-readiness.md",
  "markdown/devcontainer-readiness.md",
  "markdown/kubernetes-readiness.md",
  "markdown/gitops-readiness.md",
  "markdown/backup-readiness.md",
  "markdown/context-pack.md",
  "markdown/mcp-handoff.md",
  "markdown/agent-memory.md",
  "markdown/graph-query.md",
  "markdown/tutorial-abstractions.md",
  "markdown/decision-records.md",
  "markdown/dependency-health.md",
  "html/index.html",
  "html/learning-path.html",
  "html/files.html",
  "html/evidence.html",
  "html/suggested-reads.html",
  "html/runtime-environment.html",
  "html/interface-map.html",
  "html/symbol-map.html",
  "html/api-reference.html",
  "html/search-index.html",
  "html/learning-journal.html",
  "html/daily-summary.html",
  "html/vibe-coding-prompt-pack.html",
  "html/improvement-backlog.html",
  "html/project-activity.html",
  "html/code-metrics-readiness.html",
  "html/code-ownership-readiness.html",
  "html/large-asset-readiness.html",
  "html/license-rights.html",
  "html/sbom.html",
  "html/security-readiness.html",
  "html/sast-readiness.html",
  "html/dast-readiness.html",
  "html/threat-model-readiness.html",
  "html/scorecard.html",
  "html/provenance.html",
  "html/advisories.html",
  "html/vex.html",
  "html/policy-gates.html",
  "html/api-contracts.html",
  "html/consumer-contract-readiness.html",
  "html/observability.html",
  "html/performance.html",
  "html/profiling-readiness.html",
  "html/tracing-readiness.html",
  "html/debug-readiness.html",
  "html/crash-reporting-readiness.html",
  "html/incident-response-readiness.html",
  "html/slo-readiness.html",
  "html/cost-readiness.html",
  "html/progressive-delivery-readiness.html",
  "html/load-testing-readiness.html",
  "html/benchmark-readiness.html",
  "html/e2e.html",
  "html/flaky-test-readiness.html",
  "html/test-impact-readiness.html",
  "html/test-reporting-readiness.html",
  "html/snapshot-readiness.html",
  "html/property-based-testing-readiness.html",
  "html/fuzz-readiness.html",
  "html/test-data-readiness.html",
  "html/integration-test-environment-readiness.html",
  "html/accessibility.html",
  "html/storybook.html",
  "html/design-tokens.html",
  "html/i18n.html",
  "html/release-readiness.html",
  "html/secret-readiness.html",
  "html/secret-management-readiness.html",
  "html/container-readiness.html",
  "html/container-scan-readiness.html",
  "html/code-quality.html",
  "html/documentation.html",
  "html/database-readiness.html",
  "html/database-migration-readiness.html",
  "html/database-orm-readiness.html",
  "html/data-transformation-readiness.html",
  "html/data-quality-readiness.html",
  "html/data-lineage-readiness.html",
  "html/data-catalog-readiness.html",
  "html/data-annotation-readiness.html",
  "html/lakehouse-table-readiness.html",
  "html/feature-store-readiness.html",
  "html/model-registry-readiness.html",
  "html/experiment-tracking-readiness.html",
  "html/model-monitoring-readiness.html",
  "html/model-serving-readiness.html",
  "html/model-training-readiness.html",
  "html/ci-cd.html",
  "html/unit-tests.html",
  "html/coverage-readiness.html",
  "html/mutation-testing-readiness.html",
  "html/typecheck-readiness.html",
  "html/package-manager.html",
  "html/git-hooks.html",
  "html/task-runner.html",
  "html/dependency-updates.html",
  "html/dependency-review-readiness.html",
  "html/lint-readiness.html",
  "html/format-readiness.html",
  "html/commit-conventions.html",
  "html/changelog-readiness.html",
  "html/bundle-analysis.html",
  "html/mocking-readiness.html",
  "html/data-fetching-readiness.html",
  "html/routing-readiness.html",
  "html/state-management-readiness.html",
  "html/form-readiness.html",
  "html/auth-readiness.html",
  "html/authorization-readiness.html",
  "html/payment-readiness.html",
  "html/email-readiness.html",
  "html/queue-readiness.html",
  "html/event-stream-readiness.html",
  "html/data-connector-readiness.html",
  "html/semantic-layer-readiness.html",
  "html/bi-dashboard-readiness.html",
  "html/schema-registry-readiness.html",
  "html/stream-processing-readiness.html",
  "html/pipeline-orchestration-readiness.html",
  "html/service-mesh-readiness.html",
  "html/ingress-controller-readiness.html",
  "html/dns-readiness.html",
  "html/certificate-readiness.html",
  "html/helm-readiness.html",
  "html/admission-policy-readiness.html",
  "html/api-gateway-readiness.html",
  "html/cache-readiness.html",
  "html/logging-readiness.html",
  "html/feature-flag-readiness.html",
  "html/rate-limit-readiness.html",
  "html/error-tracking-readiness.html",
  "html/analytics-readiness.html",
  "html/http-client-readiness.html",
  "html/schema-validation-readiness.html",
  "html/datetime-readiness.html",
  "html/id-generation-readiness.html",
  "html/image-processing-readiness.html",
  "html/file-upload-readiness.html",
  "html/websocket-readiness.html",
  "html/realtime-media-readiness.html",
  "html/pdf-generation-readiness.html",
  "html/spreadsheet-readiness.html",
  "html/chart-visualization-readiness.html",
  "html/markdown-code-rendering-readiness.html",
  "html/notebook-readiness.html",
  "html/map-visualization-readiness.html",
  "html/diagram-rendering-readiness.html",
  "html/link-integrity-readiness.html",
  "html/seo-metadata-readiness.html",
  "html/pwa-readiness.html",
  "html/browser-compat-readiness.html",
  "html/browser-extension-readiness.html",
  "html/env-validation-readiness.html",
  "html/security-headers-readiness.html",
  "html/graphql-readiness.html",
  "html/cli-readiness.html",
  "html/terminal-ui-readiness.html",
  "html/state-machine-readiness.html",
  "html/animation-readiness.html",
  "html/drag-and-drop-readiness.html",
  "html/rich-text-editor-readiness.html",
  "html/command-palette-readiness.html",
  "html/guided-tour-readiness.html",
  "html/data-table-readiness.html",
  "html/calendar-readiness.html",
  "html/dialog-readiness.html",
  "html/popover-tooltip-readiness.html",
  "html/menu-dropdown-readiness.html",
  "html/toast-snackbar-readiness.html",
  "html/tabs-accordion-readiness.html",
  "html/checkbox-radio-switch-readiness.html",
  "html/slider-progress-readiness.html",
  "html/select-combobox-readiness.html",
  "html/toolbar-toggle-readiness.html",
  "html/scroll-area-readiness.html",
  "html/avatar-readiness.html",
  "html/pin-input-readiness.html",
  "html/pagination-readiness.html",
  "html/number-input-readiness.html",
  "html/rating-group-readiness.html",
  "html/color-picker-readiness.html",
  "html/splitter-readiness.html",
  "html/tags-input-readiness.html",
  "html/clipboard-readiness.html",
  "html/qr-code-readiness.html",
  "html/timer-readiness.html",
  "html/steps-readiness.html",
  "html/carousel-readiness.html",
  "html/tree-view-readiness.html",
  "html/collapsible-readiness.html",
  "html/editable-readiness.html",
  "html/password-input-readiness.html",
  "html/signature-pad-readiness.html",
  "html/angle-slider-readiness.html",
  "html/cascade-select-readiness.html",
  "html/async-list-readiness.html",
  "html/image-cropper-readiness.html",
  "html/listbox-readiness.html",
  "html/date-picker-readiness.html",
  "html/marquee-readiness.html",
  "html/toc-readiness.html",
  "html/floating-panel-readiness.html",
  "html/drawer-readiness.html",
  "html/hover-card-readiness.html",
  "html/navigation-menu-readiness.html",
  "html/presence-readiness.html",
  "html/menu-readiness.html",
  "html/tooltip-readiness.html",
  "html/llm-readiness.html",
  "html/llm-eval-readiness.html",
  "html/llm-observability-readiness.html",
  "html/vector-db-readiness.html",
  "html/search-service-readiness.html",
  "html/object-storage-readiness.html",
  "html/realtime-collaboration-readiness.html",
  "html/workflow-orchestration-readiness.html",
  "html/openapi-client-readiness.html",
  "html/webhook-readiness.html",
  "html/notification-readiness.html",
  "html/consent-readiness.html",
  "html/privacy-readiness.html",
  "html/server-framework-readiness.html",
  "html/rpc-readiness.html",
  "html/workspace-graph-readiness.html",
  "html/scaffolding-readiness.html",
  "html/scheduler-readiness.html",
  "html/build-tool-readiness.html",
  "html/styling-readiness.html",
  "html/visual-regression-readiness.html",
  "html/infrastructure-readiness.html",
  "html/iac-drift-readiness.html",
  "html/deployment-readiness.html",
  "html/serverless-readiness.html",
  "html/mobile-readiness.html",
  "html/desktop-readiness.html",
  "html/edge-readiness.html",
  "html/compose-readiness.html",
  "html/devcontainer-readiness.html",
  "html/kubernetes-readiness.html",
  "html/gitops-readiness.html",
  "html/backup-readiness.html",
  "html/context-pack.html",
  "html/mcp-handoff.html",
  "html/agent-memory.html",
  "html/graph-query.html",
  "html/tutorial-abstractions.html",
  "html/decision-records.html",
  "html/dependency-health.html",
  "html/quiz-print.html",
  "html/assets/search-index.json",
  "html/assets/learning-journal-template.md",
  "html/manifest.json",
  "html/EXPORT-README.md"
];

export async function verifyStudySessionArtifacts(sessionRoot: string): Promise<StudySessionVerificationResult> {
  const resolvedRoot = path.resolve(sessionRoot);
  const failures: StudySessionVerificationFailure[] = [];
  const session = await readSession(resolvedRoot, failures);
  const requiredArtifactsOk = await checkRequiredArtifacts(resolvedRoot, failures);
  const htmlExport = await verifyHtml(resolvedRoot, failures);
  const evidenceIndex = await verifyEvidenceIndexReport(resolvedRoot);

  for (const failure of evidenceIndex.failures) {
    failures.push({
      check: "evidence-index",
      reason: "evidence-index-failed",
      path: failure.path,
      detail: failure.detail ?? failure.reason
    });
  }

  const sessionOk = Boolean(session && session.status === "complete");
  if (session && session.status !== "complete") {
    failures.push({
      check: "session",
      reason: "incomplete-session",
      path: "session.json",
      detail: `Session status is ${session.status}.`
    });
  }

  const checks = {
    session: sessionOk,
    requiredArtifacts: requiredArtifactsOk,
    htmlExport: htmlExport?.ok ?? false,
    evidenceIndex: evidenceIndex.ok
  };

  return {
    ok: checks.session && checks.requiredArtifacts && checks.htmlExport && checks.evidenceIndex,
    sessionRoot: resolvedRoot,
    sessionId: session?.sessionId ?? null,
    checkedRequiredArtifacts: REQUIRED_ARTIFACTS.length,
    checks,
    htmlExport,
    evidenceIndex,
    failures
  };
}

async function readSession(sessionRoot: string, failures: StudySessionVerificationFailure[]): Promise<StudySession | null> {
  const sessionPath = path.join(sessionRoot, "session.json");
  let raw: string;
  try {
    raw = await fs.readFile(sessionPath, "utf8");
  } catch {
    failures.push({ check: "session", reason: "missing-session", path: "session.json" });
    return null;
  }

  try {
    return StudySessionSchema.parse(JSON.parse(raw));
  } catch (error) {
    failures.push({
      check: "session",
      reason: "invalid-session",
      path: "session.json",
      detail: error instanceof Error ? error.message : String(error)
    });
    return null;
  }
}

async function checkRequiredArtifacts(sessionRoot: string, failures: StudySessionVerificationFailure[]): Promise<boolean> {
  let ok = true;
  for (const artifactPath of REQUIRED_ARTIFACTS) {
    try {
      await fs.access(path.join(sessionRoot, artifactPath));
    } catch {
      ok = false;
      failures.push({
        check: "required-artifacts",
        reason: "missing-artifact",
        path: artifactPath
      });
    }
  }
  return ok;
}

async function verifyHtml(sessionRoot: string, failures: StudySessionVerificationFailure[]): Promise<HtmlExportVerificationResult | null> {
  try {
    const result = await verifyHtmlExportManifest(sessionRoot);
    for (const failure of result.failures) {
      failures.push({
        check: "html-export",
        reason: "html-export-failed",
        path: failure.path,
        detail: `expected ${failure.expectedBytes} bytes/${failure.expectedSha256}; actual ${failure.actualBytes ?? "missing"} bytes/${failure.actualSha256 ?? "missing"}`
      });
    }
    return result;
  } catch (error) {
    failures.push({
      check: "html-export",
      reason: "html-export-error",
      path: "html/manifest.json",
      detail: error instanceof Error ? error.message : String(error)
    });
    return null;
  }
}
