import path from "node:path";
import { markdownTableCell } from "./markdown-utils.js";

export function openTargetsMarkdown(entries: Array<{ target: string; fileName: string }>): string {
  return [
    "# RepoTutor Open Targets",
    "",
    "| Target | File |",
    "|---|---|",
    ...entries.map((entry) => `| ${markdownTableCell(entry.target)} | ${markdownTableCell(entry.fileName)} |`)
  ].join("\n");
}

export function openTargetPathsMarkdown(paths: Record<string, string>): string {
  return [
    "# RepoTutor Open Target Paths",
    "",
    "| Target | Path |",
    "|---|---|",
    ...Object.entries(paths).map(([target, filePath]) => `| ${markdownTableCell(target)} | ${markdownTableCell(filePath)} |`)
  ].join("\n");
}

export function openTargetFile(target: string): string {
  const targets = Object.fromEntries(openTargetEntries().map((entry) => [entry.target, entry.fileName]));
  const fileName = targets[target];
  if (!fileName) throw new Error(`Unsupported open target: ${target}`);
  return fileName;
}

export function openTargetEntries(): Array<{ target: string; fileName: string }> {
  return [
    { target: "index", fileName: "index.html" },
    { target: "overview", fileName: "overview.html" },
    { target: "vibe-coding-start", fileName: "vibe-coding-start.html" },
    { target: "learning-path", fileName: "learning-path.html" },
    { target: "language", fileName: "language.html" },
    { target: "architecture", fileName: "architecture.html" },
    { target: "folders", fileName: "folders.html" },
    { target: "files", fileName: "files.html" },
    { target: "evidence", fileName: "evidence.html" },
    { target: "suggested-reads", fileName: "suggested-reads.html" },
    { target: "runtime-environment", fileName: "runtime-environment.html" },
    { target: "interface-map", fileName: "interface-map.html" },
    { target: "symbol-map", fileName: "symbol-map.html" },
    { target: "api-reference", fileName: "api-reference.html" },
    { target: "search-index", fileName: "search-index.html" },
    { target: "learning-journal", fileName: "learning-journal.html" },
    { target: "daily-summary", fileName: "daily-summary.html" },
    { target: "architecture-principle-playbook", fileName: "../reference/architecture-principle-playbook.html" },
    { target: "source-to-build-interview", fileName: "../reference/source-to-build-interview.html" },
    { target: "similar-app-transfer-map", fileName: "../reference/similar-app-transfer-map.html" },
    { target: "learner-goal-alignment", fileName: "../reference/learner-goal-alignment.html" },
    { target: "ai-implementation-loop", fileName: "../reference/ai-implementation-loop.html" },
    { target: "learner-role-contract", fileName: "../reference/learner-role-contract.html" },
    { target: "ai-output-review-rubric", fileName: "../reference/ai-output-review-rubric.html" },
    { target: "vibe-coding-mastery-checklist", fileName: "../reference/vibe-coding-mastery-checklist.html" },
    { target: "vibe-coding-implementation-brief", fileName: "../reference/vibe-coding-implementation-brief.html" },
    { target: "ai-prompt-readiness-checklist", fileName: "../reference/ai-prompt-readiness-checklist.html" },
    { target: "ai-prompt-ab-lab", fileName: "../reference/ai-prompt-ab-lab.html" },
    { target: "source-retention-guide", fileName: "../reference/source-retention-guide.html" },
    { target: "source-absorption-ledger", fileName: "../reference/source-absorption-ledger.html" },
    { target: "teaching-workspace", fileName: "teaching-workspace.html" },
    { target: "vibe-coding-prompt-pack", fileName: "vibe-coding-prompt-pack.html" },
    { target: "improvement-backlog", fileName: "improvement-backlog.html" },
    { target: "project-activity", fileName: "project-activity.html" },
    { target: "code-metrics-readiness", fileName: "code-metrics-readiness.html" },
    { target: "code-ownership-readiness", fileName: "code-ownership-readiness.html" },
    { target: "large-asset-readiness", fileName: "large-asset-readiness.html" },
    { target: "license-rights", fileName: "license-rights.html" },
    { target: "sbom", fileName: "sbom.html" },
    { target: "security-readiness", fileName: "security-readiness.html" },
    { target: "sast-readiness", fileName: "sast-readiness.html" },
    { target: "dast-readiness", fileName: "dast-readiness.html" },
    { target: "threat-model-readiness", fileName: "threat-model-readiness.html" },
    { target: "scorecard", fileName: "scorecard.html" },
    { target: "provenance", fileName: "provenance.html" },
    { target: "advisories", fileName: "advisories.html" },
    { target: "vex", fileName: "vex.html" },
    { target: "policy-gates", fileName: "policy-gates.html" },
    { target: "api-contracts", fileName: "api-contracts.html" },
    { target: "consumer-contract-readiness", fileName: "consumer-contract-readiness.html" },
    { target: "observability", fileName: "observability.html" },
    { target: "performance", fileName: "performance.html" },
    { target: "profiling-readiness", fileName: "profiling-readiness.html" },
    { target: "tracing-readiness", fileName: "tracing-readiness.html" },
    { target: "debug-readiness", fileName: "debug-readiness.html" },
    { target: "crash-reporting-readiness", fileName: "crash-reporting-readiness.html" },
    { target: "incident-response-readiness", fileName: "incident-response-readiness.html" },
    { target: "slo-readiness", fileName: "slo-readiness.html" },
    { target: "cost-readiness", fileName: "cost-readiness.html" },
    { target: "progressive-delivery-readiness", fileName: "progressive-delivery-readiness.html" },
    { target: "load-testing-readiness", fileName: "load-testing-readiness.html" },
    { target: "benchmark-readiness", fileName: "benchmark-readiness.html" },
    { target: "e2e", fileName: "e2e.html" },
    { target: "flaky-test-readiness", fileName: "flaky-test-readiness.html" },
    { target: "test-impact-readiness", fileName: "test-impact-readiness.html" },
    { target: "test-reporting-readiness", fileName: "test-reporting-readiness.html" },
    { target: "snapshot-readiness", fileName: "snapshot-readiness.html" },
    { target: "property-based-testing-readiness", fileName: "property-based-testing-readiness.html" },
    { target: "fuzz-readiness", fileName: "fuzz-readiness.html" },
    { target: "test-data-readiness", fileName: "test-data-readiness.html" },
    { target: "integration-test-environment-readiness", fileName: "integration-test-environment-readiness.html" },
    { target: "chaos-engineering-readiness", fileName: "chaos-engineering-readiness.html" },
    { target: "accessibility", fileName: "accessibility.html" },
    { target: "storybook", fileName: "storybook.html" },
    { target: "design-tokens", fileName: "design-tokens.html" },
    { target: "i18n", fileName: "i18n.html" },
    { target: "release-readiness", fileName: "release-readiness.html" },
    { target: "secret-readiness", fileName: "secret-readiness.html" },
    { target: "secret-management-readiness", fileName: "secret-management-readiness.html" },
    { target: "container-readiness", fileName: "container-readiness.html" },
    { target: "container-scan-readiness", fileName: "container-scan-readiness.html" },
    { target: "code-quality", fileName: "code-quality.html" },
    { target: "documentation", fileName: "documentation.html" },
    { target: "database-readiness", fileName: "database-readiness.html" },
    { target: "database-migration-readiness", fileName: "database-migration-readiness.html" },
    { target: "database-orm-readiness", fileName: "database-orm-readiness.html" },
    { target: "data-transformation-readiness", fileName: "data-transformation-readiness.html" },
    { target: "data-quality-readiness", fileName: "data-quality-readiness.html" },
    { target: "data-lineage-readiness", fileName: "data-lineage-readiness.html" },
    { target: "data-catalog-readiness", fileName: "data-catalog-readiness.html" },
    { target: "data-annotation-readiness", fileName: "data-annotation-readiness.html" },
    { target: "lakehouse-table-readiness", fileName: "lakehouse-table-readiness.html" },
    { target: "feature-store-readiness", fileName: "feature-store-readiness.html" },
    { target: "model-registry-readiness", fileName: "model-registry-readiness.html" },
    { target: "experiment-tracking-readiness", fileName: "experiment-tracking-readiness.html" },
    { target: "model-monitoring-readiness", fileName: "model-monitoring-readiness.html" },
    { target: "model-serving-readiness", fileName: "model-serving-readiness.html" },
    { target: "model-training-readiness", fileName: "model-training-readiness.html" },
    { target: "ci-cd", fileName: "ci-cd.html" },
    { target: "unit-tests", fileName: "unit-tests.html" },
    { target: "coverage-readiness", fileName: "coverage-readiness.html" },
    { target: "mutation-testing-readiness", fileName: "mutation-testing-readiness.html" },
    { target: "typecheck-readiness", fileName: "typecheck-readiness.html" },
    { target: "package-manager", fileName: "package-manager.html" },
    { target: "git-hooks", fileName: "git-hooks.html" },
    { target: "task-runner", fileName: "task-runner.html" },
    { target: "dependency-updates", fileName: "dependency-updates.html" },
    { target: "dependency-review-readiness", fileName: "dependency-review-readiness.html" },
    { target: "lint-readiness", fileName: "lint-readiness.html" },
    { target: "format-readiness", fileName: "format-readiness.html" },
    { target: "commit-conventions", fileName: "commit-conventions.html" },
    { target: "changelog-readiness", fileName: "changelog-readiness.html" },
    { target: "bundle-analysis", fileName: "bundle-analysis.html" },
    { target: "mocking-readiness", fileName: "mocking-readiness.html" },
    { target: "data-fetching-readiness", fileName: "data-fetching-readiness.html" },
    { target: "routing-readiness", fileName: "routing-readiness.html" },
    { target: "state-management-readiness", fileName: "state-management-readiness.html" },
    { target: "form-readiness", fileName: "form-readiness.html" },
    { target: "auth-readiness", fileName: "auth-readiness.html" },
    { target: "authorization-readiness", fileName: "authorization-readiness.html" },
    { target: "payment-readiness", fileName: "payment-readiness.html" },
    { target: "email-readiness", fileName: "email-readiness.html" },
    { target: "queue-readiness", fileName: "queue-readiness.html" },
    { target: "event-stream-readiness", fileName: "event-stream-readiness.html" },
    { target: "data-connector-readiness", fileName: "data-connector-readiness.html" },
    { target: "semantic-layer-readiness", fileName: "semantic-layer-readiness.html" },
    { target: "bi-dashboard-readiness", fileName: "bi-dashboard-readiness.html" },
    { target: "schema-registry-readiness", fileName: "schema-registry-readiness.html" },
    { target: "stream-processing-readiness", fileName: "stream-processing-readiness.html" },
    { target: "pipeline-orchestration-readiness", fileName: "pipeline-orchestration-readiness.html" },
    { target: "service-mesh-readiness", fileName: "service-mesh-readiness.html" },
    { target: "ingress-controller-readiness", fileName: "ingress-controller-readiness.html" },
    { target: "dns-readiness", fileName: "dns-readiness.html" },
    { target: "certificate-readiness", fileName: "certificate-readiness.html" },
    { target: "helm-readiness", fileName: "helm-readiness.html" },
    { target: "admission-policy-readiness", fileName: "admission-policy-readiness.html" },
    { target: "api-gateway-readiness", fileName: "api-gateway-readiness.html" },
    { target: "cache-readiness", fileName: "cache-readiness.html" },
    { target: "logging-readiness", fileName: "logging-readiness.html" },
    { target: "feature-flag-readiness", fileName: "feature-flag-readiness.html" },
    { target: "rate-limit-readiness", fileName: "rate-limit-readiness.html" },
    { target: "error-tracking-readiness", fileName: "error-tracking-readiness.html" },
    { target: "analytics-readiness", fileName: "analytics-readiness.html" },
    { target: "http-client-readiness", fileName: "http-client-readiness.html" },
    { target: "schema-validation-readiness", fileName: "schema-validation-readiness.html" },
    { target: "datetime-readiness", fileName: "datetime-readiness.html" },
    { target: "id-generation-readiness", fileName: "id-generation-readiness.html" },
    { target: "image-processing-readiness", fileName: "image-processing-readiness.html" },
    { target: "file-upload-readiness", fileName: "file-upload-readiness.html" },
    { target: "websocket-readiness", fileName: "websocket-readiness.html" },
    { target: "realtime-media-readiness", fileName: "realtime-media-readiness.html" },
    { target: "pdf-generation-readiness", fileName: "pdf-generation-readiness.html" },
    { target: "spreadsheet-readiness", fileName: "spreadsheet-readiness.html" },
    { target: "chart-visualization-readiness", fileName: "chart-visualization-readiness.html" },
    { target: "markdown-code-rendering-readiness", fileName: "markdown-code-rendering-readiness.html" },
    { target: "notebook-readiness", fileName: "notebook-readiness.html" },
    { target: "map-visualization-readiness", fileName: "map-visualization-readiness.html" },
    { target: "diagram-rendering-readiness", fileName: "diagram-rendering-readiness.html" },
    { target: "link-integrity-readiness", fileName: "link-integrity-readiness.html" },
    { target: "seo-metadata-readiness", fileName: "seo-metadata-readiness.html" },
    { target: "pwa-readiness", fileName: "pwa-readiness.html" },
    { target: "browser-compat-readiness", fileName: "browser-compat-readiness.html" },
    { target: "browser-extension-readiness", fileName: "browser-extension-readiness.html" },
    { target: "env-validation-readiness", fileName: "env-validation-readiness.html" },
    { target: "security-headers-readiness", fileName: "security-headers-readiness.html" },
    { target: "graphql-readiness", fileName: "graphql-readiness.html" },
    { target: "cli-readiness", fileName: "cli-readiness.html" },
    { target: "terminal-ui-readiness", fileName: "terminal-ui-readiness.html" },
    { target: "state-machine-readiness", fileName: "state-machine-readiness.html" },
    { target: "animation-readiness", fileName: "animation-readiness.html" },
    { target: "drag-and-drop-readiness", fileName: "drag-and-drop-readiness.html" },
    { target: "rich-text-editor-readiness", fileName: "rich-text-editor-readiness.html" },
    { target: "command-palette-readiness", fileName: "command-palette-readiness.html" },
    { target: "guided-tour-readiness", fileName: "guided-tour-readiness.html" },
    { target: "data-table-readiness", fileName: "data-table-readiness.html" },
    { target: "calendar-readiness", fileName: "calendar-readiness.html" },
    { target: "dialog-readiness", fileName: "dialog-readiness.html" },
    { target: "popover-tooltip-readiness", fileName: "popover-tooltip-readiness.html" },
    { target: "menu-dropdown-readiness", fileName: "menu-dropdown-readiness.html" },
    { target: "toast-snackbar-readiness", fileName: "toast-snackbar-readiness.html" },
    { target: "tabs-accordion-readiness", fileName: "tabs-accordion-readiness.html" },
    { target: "checkbox-radio-switch-readiness", fileName: "checkbox-radio-switch-readiness.html" },
    { target: "slider-progress-readiness", fileName: "slider-progress-readiness.html" },
    { target: "select-combobox-readiness", fileName: "select-combobox-readiness.html" },
    { target: "toolbar-toggle-readiness", fileName: "toolbar-toggle-readiness.html" },
    { target: "scroll-area-readiness", fileName: "scroll-area-readiness.html" },
    { target: "avatar-readiness", fileName: "avatar-readiness.html" },
    { target: "pin-input-readiness", fileName: "pin-input-readiness.html" },
    { target: "pagination-readiness", fileName: "pagination-readiness.html" },
    { target: "number-input-readiness", fileName: "number-input-readiness.html" },
    { target: "rating-group-readiness", fileName: "rating-group-readiness.html" },
    { target: "color-picker-readiness", fileName: "color-picker-readiness.html" },
    { target: "splitter-readiness", fileName: "splitter-readiness.html" },
    { target: "tags-input-readiness", fileName: "tags-input-readiness.html" },
    { target: "clipboard-readiness", fileName: "clipboard-readiness.html" },
    { target: "qr-code-readiness", fileName: "qr-code-readiness.html" },
    { target: "timer-readiness", fileName: "timer-readiness.html" },
    { target: "steps-readiness", fileName: "steps-readiness.html" },
    { target: "carousel-readiness", fileName: "carousel-readiness.html" },
    { target: "tree-view-readiness", fileName: "tree-view-readiness.html" },
    { target: "collapsible-readiness", fileName: "collapsible-readiness.html" },
    { target: "editable-readiness", fileName: "editable-readiness.html" },
    { target: "password-input-readiness", fileName: "password-input-readiness.html" },
    { target: "signature-pad-readiness", fileName: "signature-pad-readiness.html" },
    { target: "angle-slider-readiness", fileName: "angle-slider-readiness.html" },
    { target: "cascade-select-readiness", fileName: "cascade-select-readiness.html" },
    { target: "async-list-readiness", fileName: "async-list-readiness.html" },
    { target: "image-cropper-readiness", fileName: "image-cropper-readiness.html" },
  { target: "listbox-readiness", fileName: "listbox-readiness.html" },
  { target: "date-picker-readiness", fileName: "date-picker-readiness.html" },
  { target: "marquee-readiness", fileName: "marquee-readiness.html" },
  { target: "toc-readiness", fileName: "toc-readiness.html" },
  { target: "floating-panel-readiness", fileName: "floating-panel-readiness.html" },
  { target: "drawer-readiness", fileName: "drawer-readiness.html" },
  { target: "hover-card-readiness", fileName: "hover-card-readiness.html" },
  { target: "navigation-menu-readiness", fileName: "navigation-menu-readiness.html" },
  { target: "presence-readiness", fileName: "presence-readiness.html" },
  { target: "menu-readiness", fileName: "menu-readiness.html" },
  { target: "tooltip-readiness", fileName: "tooltip-readiness.html" },
  { target: "llm-readiness", fileName: "llm-readiness.html" },
    { target: "llm-eval-readiness", fileName: "llm-eval-readiness.html" },
    { target: "llm-observability-readiness", fileName: "llm-observability-readiness.html" },
    { target: "vector-db-readiness", fileName: "vector-db-readiness.html" },
    { target: "search-service-readiness", fileName: "search-service-readiness.html" },
    { target: "object-storage-readiness", fileName: "object-storage-readiness.html" },
    { target: "realtime-collaboration-readiness", fileName: "realtime-collaboration-readiness.html" },
    { target: "workflow-orchestration-readiness", fileName: "workflow-orchestration-readiness.html" },
    { target: "openapi-client-readiness", fileName: "openapi-client-readiness.html" },
    { target: "webhook-readiness", fileName: "webhook-readiness.html" },
    { target: "notification-readiness", fileName: "notification-readiness.html" },
    { target: "consent-readiness", fileName: "consent-readiness.html" },
    { target: "privacy-readiness", fileName: "privacy-readiness.html" },
    { target: "server-framework-readiness", fileName: "server-framework-readiness.html" },
    { target: "rpc-readiness", fileName: "rpc-readiness.html" },
    { target: "workspace-graph-readiness", fileName: "workspace-graph-readiness.html" },
    { target: "scaffolding-readiness", fileName: "scaffolding-readiness.html" },
    { target: "scheduler-readiness", fileName: "scheduler-readiness.html" },
    { target: "build-tool-readiness", fileName: "build-tool-readiness.html" },
    { target: "styling-readiness", fileName: "styling-readiness.html" },
    { target: "visual-regression-readiness", fileName: "visual-regression-readiness.html" },
    { target: "infrastructure-readiness", fileName: "infrastructure-readiness.html" },
    { target: "iac-drift-readiness", fileName: "iac-drift-readiness.html" },
    { target: "deployment-readiness", fileName: "deployment-readiness.html" },
    { target: "serverless-readiness", fileName: "serverless-readiness.html" },
    { target: "mobile-readiness", fileName: "mobile-readiness.html" },
    { target: "desktop-readiness", fileName: "desktop-readiness.html" },
    { target: "edge-readiness", fileName: "edge-readiness.html" },
    { target: "compose-readiness", fileName: "compose-readiness.html" },
    { target: "devcontainer-readiness", fileName: "devcontainer-readiness.html" },
    { target: "kubernetes-readiness", fileName: "kubernetes-readiness.html" },
    { target: "gitops-readiness", fileName: "gitops-readiness.html" },
    { target: "backup-readiness", fileName: "backup-readiness.html" },
    { target: "context-pack", fileName: "context-pack.html" },
    { target: "mcp-handoff", fileName: "mcp-handoff.html" },
    { target: "agent-memory", fileName: "agent-memory.html" },
    { target: "graph-query", fileName: "graph-query.html" },
    { target: "tutorial-abstractions", fileName: "tutorial-abstractions.html" },
    { target: "decision-records", fileName: "decision-records.html" },
    { target: "dependency-health", fileName: "dependency-health.html" },
    { target: "verification", fileName: "session-verification.html" },
    { target: "coverage", fileName: "coverage.html" },
    { target: "graph", fileName: "component-graph.html" },
    { target: "component-graph", fileName: "component-graph.html" },
    { target: "incremental", fileName: "incremental.html" },
    { target: "flow", fileName: "flow.html" },
    { target: "glossary", fileName: "glossary.html" },
    { target: "rebuild", fileName: "rebuild.html" },
    { target: "quiz", fileName: "quiz.html" },
    { target: "quiz-print", fileName: "quiz-print.html" },
    { target: "wrong-notes", fileName: "wrong-notes.html" }
  ];
}

export function openTargetPaths(htmlRoot: string): Record<string, string> {
  return Object.fromEntries(openTargetEntries().map((entry) => [entry.target, path.join(htmlRoot, entry.fileName)]));
}
